# Text Embedding & Vector Storage (ChromaDB)
## Imports

In [18]:
import pandas as pd

## loading data

In [14]:

file_path="../data/raw/df_hr.csv"

df=pd.read_csv(file_path)
df.head(5)

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,2,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,4,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 672 entries, 0 to 671
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              672 non-null    int64
 1   Job Title          672 non-null    str
 2   Salary Estimate    672 non-null    str
 3   Job Description    672 non-null    str
 4   Rating             672 non-null    float64
 5   Company Name       672 non-null    str
 6   Location           672 non-null    str
 7   Headquarters       672 non-null    str
 8   Size               672 non-null    str
 9   Founded            672 non-null    int64
 10  Type of ownership  672 non-null    str
 11  Industry           672 non-null    str
 12  Sector             672 non-null    str
 13  Revenue            672 non-null    str
 14  Competitors        672 non-null    str
dtypes: float64(1), int64(2), str(12)
memory usage: 78.9 KB

## loading cleaned data

In [19]:
cleaned_file_path="../data/raw/df_hr_cleaned.csv"
import pandas as pd

df_init_cleaned=pd.read_csv(cleaned_file_path)
df_init_cleaned.head(5)

,index,Job Title,Job Description,Rating,Company Name,Location,Headquarters,Founded,Type of ownership,Industry,Sector,Competitors,Avg_Sal_K,Size_Avg,Revenue_Avg_Millions,cleaned_description
0,0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1993,Nonprofit Organization,Insurance Carriers,Insurance,"EmblemHealth, UnitedHealth Group, Aetna",154.0,3000.5,0.0,description senior data scientist responsible ...
1,1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",1968,Company - Public,Research & Development,Business Services,-1,154.0,7500.5,1500.0,secure nation ignite future join top informati...
2,2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1981,Private Practice / Firm,Consulting,Business Services,-1,154.0,3000.5,300.0,overview analysis group one largest internatio...
3,3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",154.0,750.5,300.0,job description passion data machine learning ...
4,4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",1998,Company - Private,Advertising & Marketing,Business Services,"Commerce Signals, Cardlytics, Yodlee",154.0,125.5,0.0,data scientist affinity solution marketing clo...

In [20]:
df_init_cleaned.info()

<class 'pandas.DataFrame'>
RangeIndex: 672 entries, 0 to 671
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 672 non-null    int64
 1   Job Title             672 non-null    str
 2   Job Description       672 non-null    str
 3   Rating                672 non-null    float64
 4   Company Name          672 non-null    str
 5   Location              672 non-null    str
 6   Headquarters          672 non-null    str
 7   Founded               672 non-null    int64
 8   Type of ownership     672 non-null    str
 9   Industry              672 non-null    str
 10  Sector                672 non-null    str
 11  Competitors           672 non-null    str
 12  Avg_Sal_K             672 non-null    float64
 13  Size_Avg              672 non-null    float64
 14  Revenue_Avg_Millions  672 non-null    float64
 15  cleaned_description   672 non-null    str
dtypes: float64(4), int64(2), str(10)
memory usage: 84.1 KB